WIM/urls.py
from django.contrib import admin
from django.urls import path, include

from water import views as water_views
from hoteladmin import views as hoteladmin_views

urlpatterns = [
    path('', hoteladmin_views.LogIn, name='LogIn'),
    path('logout', hoteladmin_views.RemoveSession, name='LogOut'),
    path('admin/', admin.site.urls),
    path('water/', include('water.urls')),
    path('hoteladmin/', include('hoteladmin.urls')),

]

water/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.LoadHome, name='load_home'),
    path('home', views.LoadHome, name='load_home'),
    path('status', views.LoadStatus, name='load_status'),
    path('sellBottleMethod', views.sellBottleMethod, name='sellBottleMethod'),
    # path('newBottleForm', views.newBottleMethod, name='newBottleMethod'),
    path('addNewStock', views.addNewStockMethod, name='addNewStockMethod'),
    path('createNewBottle', views.createNewBottleMethod, name='createNewBottleMethod'),
    path('filtersearch', views.FilterSearch_middleware, name='FilterSearch'),
    path('historydetailsundo', views.HistoryDetailsUndo, name='HistoryDetailsUndo'),
    path('sellbottlecomplimentary', views.sellBottleComplimentary, name='sellBottleComplimentary'),
    path('remove_entry/', views.remove_entry, name='remove_entry'),

]

water/models.py
from django.db import models


# Create your models here.

class ROOM(models.Model):
    room_no = models.CharField(max_length=20, primary_key=True)

    def __str__(self):
        return self.room_no


class BRAND(models.Model):
    brand_name = models.CharField(max_length=20, primary_key=True)

    def __str__(self):
        return self.brand_name


class SIZE(models.Model):
    bottle_size = models.DecimalField(decimal_places=2, max_digits=4, primary_key=True)

    def __str__(self):
        return str(self.bottle_size)


class BOTTLE(models.Model):
    brand_name = models.ForeignKey(BRAND, on_delete=models.CASCADE)
    bottle_size = models.ForeignKey(SIZE, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.brand_name) + " | " + str(self.bottle_size) + "L"


class BOTTLE_DETAILS(models.Model):
    bottle = models.ForeignKey(BOTTLE, on_delete=models.CASCADE)
    buy_price = models.DecimalField(max_digits=4, decimal_places=2)
    sell_price = models.DecimalField(max_digits=4, decimal_places=2, null=True)

    def __str__(self):
        return str(self.bottle) + " | " + str(self.buy_price) + "Tk"


class STOCK(models.Model):
    stock_name = models.OneToOneField(BOTTLE_DETAILS, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return str(self.stock_name)


class HISTORY(models.Model):
    room = models.ForeignKey(ROOM, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.room) + " " + str(self.date)


class HISTORYDETAIL(models.Model):
    history = models.ForeignKey(HISTORY, on_delete=models.CASCADE)
    bottle_detail = models.ForeignKey(BOTTLE_DETAILS, on_delete=models.CASCADE, default=None)
    quantity = models.IntegerField(null=True)
    notcomplimentary = models.IntegerField(default=1)
    def __str__(self):
        return str(self.history)

water/forms.py
import datetime
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Row, Column, Div, Field, ButtonHolder, Button
from django import forms
from .models import *


# This is widget specifically built for DatePicker
class DatePicker(forms.DateInput):
    input_type = 'date'


# This form is used to sell a product. The ROOM is taken as input to store
# the history of the sold products to a certain room
class SellBottleForm(forms.Form):
    room = forms.ModelChoiceField(queryset=ROOM.objects.all().order_by('room_no'), initial=0)
    bottle = forms.ModelChoiceField(queryset=BOTTLE.objects.all(), initial=0)
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Quantity'}))
    date = forms.DateField(initial=datetime.date.today(), widget=DatePicker)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Div(
                Column('room', css_class='custom-select col ms-2'),
                Column('bottle', css_class='custom-select col ms-2'),
                Column('quantity', css_class='custom-select col ms-2'),
                Column('date', css_class='col ms-2'),

                css_class='d-flex justify-content-evenly align-content-center m-2'
            ),
            Div(
                Button('complimentary', 'Complimentary', css_class='btn-dark btn-outline-success text-white m-sm-3'),
                Button('sell', 'Sell Bottle', css_class='btn-dark btn-outline-success text-white m-sm-3'),
                # Button('undo', 'Undo', css_class='btn-dark btn-outline-success text-white m-sm-3'),
                css_class='d-flex justify-content-center align-content-center m-2',
            ),
        )


# This form is used to create a new record in the STOCK table. If the record
# already exists then the input quantity is used to increase the stock amount
# of the respective product.
class AddNewStock(forms.Form):
    stock = forms.ModelChoiceField(queryset=BOTTLE_DETAILS.objects.all().order_by('bottle__brand_name'))
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Quantity'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Div(
                Column('stock', css_class='custom-select col mx-2'),
                Column('quantity', css_class='col mx-2', placeholder='Quantity'),
                css_class='form-row d-flex justify-content-center align-content-center mb-2'
            ),
            Div(
                Button('add-stock', 'Add Stock', css_class='btn-dark btn-outline-success text-white mb-3'),
                css_class='d-flex justify-content-center align-content-center',
            ),

        )




class HistoryTableSearchBarForm(forms.Form):
    DateFrom = forms.DateField(widget=DatePicker, label="From")
    DateTo = forms.DateField(widget=DatePicker, label="To")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Row(
                Column(
                    Div('DateFrom', css_class='col-3 mx-2', data_label_text="From"),
                    Div('DateTo', css_class='col-3 mx-2', data_label_text="To"),
                    Button('history-filter', 'Filter', css_class='btn-dark btn-outline-success text-white mb-3 mx-2'),
                    css_class='d-flex justify-content-center'
                ),

            )
        )

water/views.py
from datetime import date
import json
import requests
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

from hoteladmin.views import LogIn
from .forms import *
from hoteladmin.forms import *
from django.core import serializers


# Create your views here.

# class VAR:
#     undo_id = []


def index(request):
    # form = stockForm()
    # form = addNewStock()

    context = {
        'SellBottleForm': SellBottleForm(),
        'AddNewStock': AddNewStock(),
        'CreateNewBottleForm': CreateNewBottleForm(),
    }
    # return render(request, 'water/createNewBottleForm.html', context)
    return render(request, 'hoteladmin/admin.html', context)
    # return render(request, 'water/sellBottleForm.html', context)
    # return render(request, 'water/addNewStock.html', context)


# this method loads the home page
def LoadHome(request):
    if 'username' in request.session:
        if request.session['designation'] != 'ceo':

            if 'dFrom' in request.session:
                del request.session['dFrom']
                del request.session['dTo']

            context = {
                'SellBottleForm': SellBottleForm(),
                'history': getHistory(),
                'historyTableFilterBar': HistoryTableSearchBarForm(),
                'ceo': 0,
            }

            if request.session['designation'] == 'ceo':
                context['ceo'] = 1

            return render(request, 'water/home.html', context)
    return redirect(LogIn)


# this method loads the status page
def LoadStatus(request):
    if 'username' in request.session:
        if request.session['designation'] != 'ceo':
            StockTable, bottleSize = GetStockTableInfo()
            context = {
                'AddNewStock': AddNewStock(),
                'CreateNewBottleForm': CreateNewBottleForm(),
                'StockTable': StockTable,
                'bottleSize': bottleSize,
            }
            if request.session['designation'] == 'ceo':
                context['ceo'] = 1
            return render(request, 'water/status.html', context)
    else:
        return redirect(LogIn)


# This method is used to sell bottles and record the history in the
# HISTORY, HISTORY_DETAILS table.
def sellBottleMethod(request, notComp=1):
    notEnough = 0
    if request.method == "POST":
        form = SellBottleForm(request.POST)

        if form.is_valid():

            room = form.cleaned_data['room']
            bottle = form.cleaned_data['bottle']
            quantity = form.cleaned_data['quantity']
            sellDate = form.cleaned_data['date']
            bottle_details = BOTTLE_DETAILS.objects.filter(bottle_id=bottle.pk).order_by('buy_price')

            executed = False

            # add to history
            sellHistory = HISTORY(room_id=room, date=sellDate)

            sellHistory.save()

            # add to HISTORY_DETAILS

            if len(bottle_details) != 0:
                totalBottleStock = 0

                # counting the total same types of bottles with different stockIn pricing
                # and checking afterwards if that total bottle number is sufficient for
                # the request to fulfill

                for bottleDetailsObj in bottle_details:
                    bottleStockObj = STOCK.objects.filter(stock_name_id=bottleDetailsObj.pk)
                    if len(bottleStockObj) != 0:
                        # getting the record from QuerySet by indexing
                        bottleStockObj = bottleStockObj[0]
                        totalBottleStock += bottleStockObj.quantity

                if totalBottleStock >= quantity:
                    notEnough = 1
                    for bottleDetailsObj in bottle_details:
                        bottleStockObj = STOCK.objects.filter(stock_name_id=bottleDetailsObj.pk)
                        # check if that record of BOTTLE_HISTORY exists in the STOCK table
                        # As BOTTLE_HISTORY and STOCK table are in one-to-one relationship
                        # the returned QuerySet will either contain 1 value or 0 value. Hence
                        # checking by != 0 means if there ary any value in the QuerySet.
                        if len(bottleStockObj) != 0:

                            # getting the record from QuerySet by indexing
                            bottleStockObj = bottleStockObj[0]
                        else:
                            # ============ SEND MESSAGE TO USER ==================
                            # ########## THE BOTTLE IS NOT IN STOCK ##############
                            # ====================================================
                            # print("The bottle is not in stock")
                            break

                        # if the stock amount is greater than the requested quantity then decrease
                        # the stock count by quantity. Finally update the STOCK record. To update
                        # we need to specify the 'id'. 'id' is the primary-key of that STOCK record.
                        # If not mentioned, dJango will execute the command as a new object and add
                        # a new record

                        if bottleStockObj.quantity <= quantity:
                            # add to HISTORY_DETAIL table
                            history_details = HISTORYDETAIL(history=sellHistory, bottle_detail=bottleDetailsObj,
                                                            quantity=quantity, notcomplimentary=notComp)
                            history_details.save()

                            quantity -= bottleStockObj.quantity

                            bottleStockObj = STOCK(id=bottleStockObj.pk, stock_name_id=bottleStockObj.stock_name_id,
                                                   quantity=0)
                            bottleStockObj.save()

                            # VAR.undo_id.append(history_details.pk)
                            tempList = request.session["undo_id"]
                            tempList.append(history_details.pk)
                            request.session["undo_id"] = tempList
                            # request.session['undo_id'].append(history_details.pk)
                            # print(f'undo id --- {request.session["undo_id"]}')
                            executed = True
                        else:
                            bottleStockObj = STOCK(id=bottleStockObj.pk, stock_name_id=bottleStockObj.stock_name_id,
                                                   quantity=bottleStockObj.quantity - quantity)
                            bottleStockObj.save()

                            # add to HISTORY_DETAIL table
                            history_details = HISTORYDETAIL(history=sellHistory, bottle_detail=bottleDetailsObj,
                                                            quantity=quantity, notcomplimentary=notComp)
                            history_details.save()
                            # VAR.undo_id.append(history_details.pk)
                            tempList = request.session["undo_id"]
                            tempList.append(history_details.pk)
                            request.session["undo_id"] = tempList
                            executed = True
                            break
                # if not executed:
                #     # ================= SEND MESSAGE TO USER =================
                #     # ============ NOT SUFFICIENT BOTTLE IN STOCK ============
                #     # ========================================================
                #     print("Not sufficient bottle in stock")
                else:
                    notEnough = 0

    context = {}
    context['status'] = notEnough
    if 'dFrom' in request.session:
        context['history'] = FilterSearch(request, False)['history']
    else:
        context['history'] = getHistory()

    return JsonResponse(context)


# this method is for selling the complimentary bottles
def sellBottleComplimentary(request):
    jsonVar = sellBottleMethod(request, 0)
    return jsonVar


# This method is used to add a certain amount of products
# in the stock. == addNewStockMethod() ==
def addNewStockMethod(request):
    if request.method == 'POST':
        form = AddNewStock(request.POST)
        if form.is_valid():

            bottleDetailsObject_PK = request.POST['stock']
            stockQuantity = form.cleaned_data['quantity']
            bottleDetailsObject = form.cleaned_data['stock']

            # check if the stock exists with the following if-else
            # if stock does not exist
            if len(STOCK.objects.filter(stock_name_id=bottleDetailsObject_PK)) == 0:
                # create a new STOCK instance and save it.
                newStock = STOCK(quantity=stockQuantity, stock_name=bottleDetailsObject)
                newStock.save()

            # if stock exists
            else:
                # fetch the stock object using foreign key and use it afterwards to access
                # the initial quantity via 'existingStock'
                existingStock = STOCK.objects.filter(stock_name_id=bottleDetailsObject_PK)[0]
                existingStock = STOCK(id=existingStock.pk, stock_name_id=bottleDetailsObject_PK,
                                      quantity=existingStock.quantity + stockQuantity)
                existingStock.save()

        # else:
        #     print("Form is not valid")
    StockTable, bottleSize = GetStockTableInfo()
    context = {
        'status': 1,
        'StockTable': StockTable,
        'bottleSize': bottleSize,
    }
    return JsonResponse(context)


# This method is used to create a new instance of bottle and
# create a new record of bottle in the BOTTLE table.
# == createNewBottleMethod() ==
def createNewBottleMethod(request):
    if request.method == "POST":

templates/water/HistoryTableSearchBar.html
{% load crispy_forms_tags %}
<div class="container my-sm-2">
    <div class="shadow-lg p-3 m-1 bg-body rounded">
        {#        {% crispy historyTableFilterBar %}#}
        <div class="row d-flex justify-content-between">
            <div class="col-4">
                <div class="form-floating">
                    <input type="date" class="form-control" id="id_DateFrom"
                           name="dashboard_from"
                           placeholder="From">
                    <label for="id_DateFrom">From</label>
                </div>
            </div>
            <div class="col-4">
                <div class="form-floating">
                    <input type="date" class="form-control" id="id_DateTo"
                           name="dashboard_from"
                           placeholder="From">
                    <label for="id_DateTo">To</label>
                </div>
            </div>
            <div class="col-2">
                <input type="button" name="history-filter" value="Filter"
                       class="btn btn-dark btn-outline-success text-white me-2 mt-2" id="button-id-history-filter">
            </div>

        </div>


    </div>
</div>

templates/water/historyTable.html
{% include 'commonHTML/confirm_delete.html' %}

<div class="container my-sm-2">
    <div class="col-sm shadow-lg p-3 m-1 bg-body rounded">
        <table class="table table-hover " id="history_table_id">

            <thead>
            <tr>
                <th class="col"> Date</th>
                <th class="col"> Room</th>
                <th class="col"> Bottle</th>
                <th class="col"> Quantity</th>
                <th class="col"></th>
            </tr>
            </thead>

            <tbody id="history-table-body">

            {% for date,rooms in history.items %}

                <tr>
                    <td>
                        {{ date }}
                    </td>

                    {% for room,info in rooms.items %}

                        <td>{{ room }}</td>
                        <td>
                            <table>
                                {% for bottle_name in info.bottle %}
                                    <tr>
                                        <td>{{ bottle_name }}</td>
                                    </tr>
                                {% endfor %}
                            </table>

                        </td>
                        <td>
                            <table>
                                {% for bottle_quantity in info.quantity %}
                                    <tr>
                                        <td>
                                            {{ bottle_quantity }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </td>
                        <td>
                            <table>
                                {% for history_detail_id in info.history_detail_id %}
                                    <tr>
                                        <td>
                                            <a class="btn-remove-entry text-danger"
                                               href="#"
                                               data-history-detail="{{ history_detail_id }}"
                                               data-bs-target="#confirm_delete_modal"
                                               data-bs-toggle="modal">

                                                <i class="bi bi-trash"></i>
                                            </a>
                                        </td>

                                    </tr>

                                {% endfor %}
                            </table>

                        </td>
                        </tr>
                        <tr>
                        <td></td>
                    {% endfor %}

                    </tr>

            {% endfor %}

            </tbody>

        </table>
    </div>
</div>

templates/water/home.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block SellBottleFormContent %}
    {# ====== THIS CODE HERE IS FOR SellBottleForm() =========== #}

    <div class="container my-sm-2">
        <div class="d-flex justify-content-center align-content-center">
            <div class="col-sm shadow-lg p-3 m-1 bg-body rounded">
                <fieldset class="border p-sm-2 form-group">
                    <legend class="w-auto float-none" id="Legend5">
                        Sell Bottle
                    </legend>
                    {% crispy SellBottleForm %}
                </fieldset>
            </div>
        </div>
    </div>

    {# ========================================================== #}
    {% include 'water/HistoryTableSearchBar.html'%}

    {% include 'water/historyTable.html' %}

{% endblock %}

templates/water/status.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block newBottle_stockIn %}


    {# ====== THIS FORM HERE IS FOR CreateNewBottleForm() and StockInForm() ======#}

    <div class="container">

        <div class="row d-flex justify-content-center mt-2">

            {#         ========= THIS FORM IS FOR StockInForm() ===========#}
            <div class="col-sm me-1 shadow-lg p-3 bg-body rounded">
                <fieldset class="border p-sm-2 form-group">
                    <legend class="w-auto float-none" id="Legend5">
                        Stock in
                    </legend>
                    <form method="POST" id="create-Stock">
                        {% crispy AddNewStock %}

                    </form>

                </fieldset>
            </div>
            {#         =========================================================#}

            {#         =========== THIS BOTTLE IS FOR CreateBottleForm() ============#}
            <div class="col-sm ms-1 shadow-lg p-3 bg-body rounded">

                <fieldset class="border p-sm-2 form-group">
                    <legend class="w-auto float-none" id="Legend5">
                        New Bottle
                    </legend>

                    <form method="POST" id="create-new-bottle">
                        {% crispy CreateNewBottleForm %}

                    </form>

                </fieldset>

            </div>
            {#         =========================================================#}
        </div>
    </div>

    {# =====================================================================#}


    {% include 'water/stockTable.html' %}


{% endblock %}

templates/water/stockTable.html
<div class="container">
    <div class="row d-flex justify-content-center mt-2">
        <div class="shadow-lg p-3 bg-body rounded flex-grow-1">
            <div class="text-center">
                <p>
                <h4>Stock Report</h4>
                </p>
            </div>
            <table class="table table-hover ">

                <thead id="stock-table-head">
                <th class="col"> Brand/Size</th>
                {% for key,value in bottleSize.items %}
                    <th class="col"> {{ key }} L</th>
                {% endfor %}
                </thead>

                <tbody id="stock-table-body">

                {% for key,value in StockTable.items %}
                    <tr>
                        <td>
                            {{ key }}
                        </td>
                        {% for bottle,size in value.items %}
                            <td>
                                {{ size }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}

                </tbody>

            </table>

        </div>
    </div>
</div>