WIM/urls.py
from django.contrib import admin
from django.urls import path, include

from water import views as water_views
from hoteladmin import views as hoteladmin_views

urlpatterns = [
    path('', hoteladmin_views.LogIn, name='LogIn'),
    path('logout', hoteladmin_views.RemoveSession, name='LogOut'),
    path('admin/', admin.site.urls),
    path('water/', include('water.urls')),
    path('hoteladmin/', include('hoteladmin.urls')),

]

hoteladmin/urls.py
from django.contrib import admin
from django.urls import path, include

import water.views
import hoteladmin.views
from water.views import *

urlpatterns = [
    path('', hoteladmin.views.LoadDashboard, name='LoadAdmin'),
    path('deletebottledetails', hoteladmin.views.DeleteBottleDetails, name='DeleteBottleDetails'),
    path('createbrand', hoteladmin.views.CreateBrand, name='CreateBrand'),
    path('deletebrand', hoteladmin.views.DeleteBrand, name='DeleteBrand'),
    path('createsize', hoteladmin.views.CreateSize, name='CreateSize'),
    path('deletesize', hoteladmin.views.DeleteSize, name="DeleteSize"),
    path('dashboard', hoteladmin.views.LoadDashboard, name='LoadDashboard'),

]

hoteladmin/models.py
from django.db import models

# Create your models here.

class USER(models.Model):
    username = models.CharField(max_length=20, primary_key=True)
    password = models.CharField(max_length=50)
    designation = models.CharField(max_length=20)

    def __str__(self):
        return self.username + " | " + self.designation

hoteladmin/forms.py
import datetime
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Row, Column, Div, Field, ButtonHolder, Button
from django import forms
from water.models import *


# This is widget specifically built for DatePicker
class DatePicker(forms.DateInput):
    input_type = 'date'


# This form is used ot create a new record in the BOTTLE table
class CreateNewBottleForm(forms.Form):
    brand = forms.ModelChoiceField(queryset=BRAND.objects.all(), initial=0)
    size = forms.ModelChoiceField(queryset=SIZE.objects.all(), initial=0)
    buyPrice = forms.DecimalField(max_digits=4, decimal_places=2,
                                  widget=forms.TextInput(attrs={'placeholder': 'Buying Price'}))
    sellPrice = forms.DecimalField(max_digits=4, decimal_places=2,
                                   widget=forms.TextInput(attrs={'placeholder': 'Selling Price'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.form_id = 'createBottle'
        # self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(
                Column('brand', css_class='custom-select col mx-2'),
                Column('size', css_class='custom-select col mx-2'),
                css_class='form-row d-flex justify-content-center align-content-center mb-2'
            ),
            Div(
                Div('buyPrice', css_class='col-3 mx-2'),
                Div('sellPrice', css_class='col-3 mx-2'),
                # Submit('submit', 'Create', css_class='btn-secondary btn-outline-success text-white mb-3 mx-2'),
                Button('create-bottle', 'Create', css_class='btn-dark btn-outline-success text-white mb-3 mx-2'),
                css_class='form-row d-flex justify-content-center align-content-center'
            )
        )


# This form is for creating new brand
class CreateBrandForm(forms.Form):
    brand = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Enter Here'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column('brand', css_class='col-8 my-2 mx-2'),
                Div(
                    Button('create-brand', 'Create', css_class='btn btn-dark my-2 mx-2'),
                    css_class='col'
                ),

                css_class="d-flex justify-content-center align-content-center text-wrap my-2"
            )
        )

    # This form is for creating new size


# This form is for creating new record in SIZE table
class CreateSizeForm(forms.Form):
    size = forms.DecimalField(max_digits=4, decimal_places=2,
                              widget=forms.TextInput(attrs={'placeholder': 'Enter Here'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column('size', css_class='col-8 my-2 mx-2'),
                Div(
                    Button('create-size', 'Create', css_class='btn btn-dark my-2 mx-2'),
                    css_class='col'
                ),

                css_class="d-flex justify-content-center align-content-center text-wrap my-2"
            )
            # Div(
            #     Column('size', css_class='col mb-3 mx-2'),
            #     # Submit('submit', 'Create', css_class='btn-secondary btn-outline-success text-white mb-3 mx-2'),
            #     Button('create-size', 'Create', css_class='btn-sm btn-dark mb-3 mx-2'),
            #     css_class='form-row d-flex justify-content-center align-content-center'
            # )
        )

hoteladmin/views.py
from datetime import date

from django.db.models import Sum
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

import water
from water.forms import *
from water.views import *
import water.views as water_views
from .models import *
from .forms import *




# this method is for loading the Dashboard page [ ADMIN PAGE ]
def LoadDashboard(request):
    if 'username' in request.session:
        if request.session['designation'] == 'ceo':

            # this if is for Dashboard Data filtration
            from_date = ""
            to_date = ""
            bottleDetails = list(BOTTLE_DETAILS.objects.all())
            BrandForm = CreateBrandForm()
            StockTable, bottleSize = water_views.GetStockTableInfo()
            if request.method == 'POST':
                from_date = request.POST['dashboard_from']
                to_date = request.POST['dashboard_to']
                tableInfo, profitInfo, quantityInfo, totalSold, totalProfit = GetDashboardTable(from_date, to_date)
            else:
                tableInfo, profitInfo, quantityInfo, totalSold, totalProfit = GetDashboardTable()

            context = {
                'table': tableInfo,
                'profitInfo': profitInfo,
                'quantityInfo': quantityInfo,
                'totalSold': totalSold,
                'totalProfit': totalProfit,
                'fromDate': from_date,
                'toDate': to_date,
                'BottleDetails': bottleDetails,
                'BrandForm': CreateBrandForm(),
                'SizeForm': CreateSizeForm(),
                'brand': list(BRAND.objects.all()),
                'StockTable': StockTable,
                'bottleSize': bottleSize,
                'size': list(SIZE.objects.all()),
                'ceo': 1,
            }

            GetDashboardTable()
            if request.session['designation'] == 'ceo':
                context['ceo'] = 1

            return render(request, 'hoteladmin/Dashboard.html', context)
    else:
        return redirect(water_views.LoadHome)


# this method is for fetching the data for "Dashboard Bottle Report" and Pie Chart
def GetDashboardTable(from_date=None, to_date=None):
    #     history = list(HISTORY.objects.filter(date__gte=dFrom, date__lte=dTo).values())
    allHistoryDetails = 0
    if from_date is not None:
        allHistoryDetails = HISTORYDETAIL.objects.filter(history__date__gte=from_date, history__date__lte=to_date)
    else:
        allHistoryDetails = list(HISTORYDETAIL.objects.all())
    contextQuantity = {}
    contextSold = {}
    contextProfit = {}
    contextBuy = {}
    # for counting quantity
    for data in allHistoryDetails:
        if str(BOTTLE_DETAILS.objects.get(id=data.bottle_detail.pk).bottle) not in contextQuantity:
            contextQuantity[str(BOTTLE_DETAILS.objects.get(id=data.bottle_detail.pk).bottle)] = data.quantity
            contextBuy[str(BOTTLE_DETAILS.objects.get(
                id=data.bottle_detail.pk).bottle)] = float(data.bottle_detail.buy_price * data.quantity)
            contextSold[str(BOTTLE_DETAILS.objects.get(
                id=data.bottle_detail.pk).bottle)] = float(data.bottle_detail.sell_price * data.notcomplimentary * data.quantity)
        else:
            contextQuantity[str(BOTTLE_DETAILS.objects.get(id=data.bottle_detail.pk).bottle)] += data.quantity
            contextBuy[str(BOTTLE_DETAILS.objects.get(
                id=data.bottle_detail.pk).bottle)] += float(data.bottle_detail.buy_price * data.quantity)
            contextSold[str(BOTTLE_DETAILS.objects.get(
                id=data.bottle_detail.pk).bottle)] += float(
                data.bottle_detail.sell_price * data.quantity * data.notcomplimentary)

    for bottle in contextQuantity.keys():
        contextProfit[bottle] = contextSold[bottle] - contextBuy[bottle]

    context = {}
    totalSold = 0
    totalProfit = 0
    for bottle in contextQuantity.keys():
        context[bottle] = []
        context[bottle].append(bottle)
        context[bottle].append(contextQuantity[bottle])
        context[bottle].append(contextSold[bottle])
        context[bottle].append(contextProfit[bottle])
        totalSold += contextSold[bottle]
        totalProfit += contextProfit[bottle]

    return context, contextProfit, contextQuantity, totalSold, totalProfit


# this method here is for deleting objects in BOTTLE_DETAILS table
def DeleteBottleDetails(request):
    StockTable, bottleSize = water_views.GetStockTableInfo()
    if request.method == "POST":
        id = request.POST.get('sid')
        object = BOTTLE_DETAILS.objects.get(pk=id)
        object.delete()
        context = {
            'status': 1,
            'StockTable': StockTable,
            'bottleSize': bottleSize,
        }
    else:
        context = {
            'status': 0,
            'StockTable': StockTable,
            'bottleSize': bottleSize,
        }
    return JsonResponse(context)


# this method here is for creating new record of BRAND table
def CreateBrand(request):
    context = {
        'status': 0
    }
    if request.method == "POST":
        BrandForm = CreateBrandForm(request.POST)
        if BrandForm.is_valid():
            context['status'] = 1
            brand = BrandForm.cleaned_data['brand']
            object = BRAND(brand_name=brand)
            object.save()
            context['status'] = 1
    # context['brand'] = serializers.serialize('json',list(BRAND.objects.all()))
    context['brand'] = list(BRAND.objects.values())
    StockTable, bottleSize = water_views.GetStockTableInfo()

    context['bottleSize'] = bottleSize
    context['StockTable'] = StockTable

    return JsonResponse(context)


# this method is for deleting a brand
def DeleteBrand(request):
    context = {
        'status': 0
    }
    if request.method == "POST":
        id = request.POST['sid']
        object = BRAND.objects.get(pk=id)
        object.delete()
        context['status'] = 1
    StockTable, bottleSize = water_views.GetStockTableInfo()

    context['bottleSize'] = bottleSize
    context['StockTable'] = StockTable

    return JsonResponse(context)


# this method is for creating a record of size
def CreateSize(request):
    context = {
        'status': 0
    }
    if request.method == "POST":
        SizeForm = CreateSizeForm(request.POST)
        if SizeForm.is_valid():
            context['status'] = 1
            size = SizeForm.cleaned_data['size']
            object = SIZE(bottle_size=size)
            object.save()
            context['status'] = 1
    # context['brand'] = serializers.serialize('json',list(BRAND.objects.all()))
    context['sizeTable'] = list(SIZE.objects.values())
    StockTable, bottleSize = water_views.GetStockTableInfo()

    context['bottleSize'] = bottleSize
    context['StockTable'] = StockTable

    return JsonResponse(context)


# this method is for deleting record of size
def DeleteSize(request):
    context = {
        'status': 0
    }
    if request.method == "POST":
        id = request.POST['sid']
        object = SIZE.objects.get(pk=id)
        object.delete()
        context['status'] = 1
    StockTable, bottleSize = water_views.GetStockTableInfo()
    context['sizeTable'] = list(SIZE.objects.values())
    context['bottleSize'] = bottleSize
    context['StockTable'] = StockTable

    return JsonResponse(context)


# this method is for creating new session
def CreateNewSession(request, username, designation):
    request.session['username'] = username
    request.session['designation'] = designation
    request.session['undo_id'] = []


# the cookies of the sessions are removed here
def RemoveSession(request):
    request.session.flush()
    request.session.clear_expired()
    return redirect(LogIn)


# this method is for user authentication
def LogIn(request):
    # if an user is already logged in and requests the login page then
    # first check if any user is already logged. If an user is logged
    # then redirect him to his corresponding home page. Otherwise restrict
    # him to go to any page without user authentication
    if 'username' in request.session:
        # Check which type of user is already logged and then redirect them
        # to their corresponding Home Page
        if request.session['designation'] == 'ceo':
            return redirect(LoadDashboard)
        else:
            return redirect(water_views.LoadHome)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = USER.objects.filter(username=username, password=password)
        if len(user) == 0:
            return redirect(LogIn)
        else:
            user = list(user.values())[0]
            CreateNewSession(request, user['username'], user['designation'])
            if user['designation'] == 'ceo':
                return redirect(LoadDashboard)
            else:
                return redirect(water_views.LoadHome)

    return render(request, 'commonHTML/LogIn.html', {})

templates/hoteladmin/AdminBottleTable.html
<div class="col-sm-5">
    <div class="card border-light border-light mb-3 shadow rounded-3">
        <div class="card-header rounded-3">
            <div class="text-center">
                <h5>Bottle</h5>
            </div>
        </div>
        <div class="card-body text-dark">

            <table class="table table-hover ">
                <thead>
                <tr>
                    <th class="col">
                        <div class="text-center">
                            Type
                        </div>
                    </th>
                    <th class="col">
                        <div class="text-center">
                            Action
                        </div>
                    </th>
                </tr>
                </thead>
                <tbody id="admin-bottle-table-body">

                {% for bottle in BottleDetails %}
                    <tr>
                        <td>{{ bottle }}</td>
                        <td>
                            <div class="text-center">
                                <input type="button" class="btn-sm btn-dark btn-del" data-sid="{{ bottle.id }}" value="Delete">
                            </div>

                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>


        </div>
    </div>
</div>

templates/hoteladmin/AdminBrandTable.html
<div class="col">
    <div class="card border-light border-light shadow rounded-3">
        <div class="card-header rounded-3">
            <div class="text-center">
                <h5>Brand</h5>
            </div>
        </div>
        <div class="card-body text-dark">

            <table class="table table-hover ">
                <thead>
                <tr>
                    <th class="col">
                        <div class="text-center">
                            Name
                        </div>
                    </th>
                    <th class="col">
                        <div class="text-center">
                            Action
                        </div>
                    </th>
                </tr>
                </thead>
                <tbody id="admin-brand-table-body">

                {% for brand_name in brand %}
                    <tr><td class="col"><div class="text-center">
                                {{ brand_name }}
                            </div></td><td><div class="text-center"><input type="button" class="btn-sm btn-dark btn-del" data-sid="{{ brand_name }}" value="Delete"></div></td></tr>
                {% endfor %}

                </tbody>
            </table>


        </div>
    </div>
</div>

templates/hoteladmin/AdminSizeTable.html
<div class="col">
    <div class="card border-light border-light shadow rounded-3">
        <div class="card-header rounded-3">
            <div class="text-center">
                <h5>Size</h5>
            </div>
        </div>
        <div class="card-body text-dark">

            <table class="table table-hover ">
                <thead>
                <tr>
                    <th class="col">
                        <div class="text-center">
                            Name
                        </div>
                    </th>
                    <th class="col">
                        <div class="text-center">
                            Action
                        </div>
                    </th>
                </tr>
                </thead>
                <tbody id="admin-size-table-body">

                {% for bottle_size in size %}
                    <tr><td class="col"><div class="text-center">
                                {{ bottle_size }} L
                            </div></td><td><div class="text-center"><input type="button" class="btn-sm btn-dark btn-del" data-sid="{{ bottle_size }}" value="Delete"></div></td></tr>
                {% endfor %}

                </tbody>
            </table>


        </div>
    </div>
</div>

templates/hoteladmin/AdminStockInTable.html
<div class="col-sm-7">
    <div class="card border-light border-light mb-3 shadow rounded-3">
        <div class="card-header rounded-3">
            <div class="text-center">
                <h5>Stock In</h5>
            </div>
        </div>
        <div class="card-body text-dark">

            <table class="table table-hover ">
                <thead>
                <tr>
                    <th class="col">
                        <div class="text-center">
                            Staff Name
                        </div>
                    </th>
                    <th class="col">
                        <div class="text-center">
                            Type
                        </div>
                    </th>
                    <th class="col">
                        <div class="text-center">
                            Quantity
                        </div>
                    </th>
                    <th class="col">
                        <div class="text-center">
                            Action
                        </div>
                    </th>
                </tr>
                </thead>
                <tbody>


                <tr>
                    <td>
                        <div class="text-center">
                            Ashraful Islam
                        </div>

                    </td>
                    <td>MUM 0.5L 6Tk</td>
                    <td>
                        <div class="text-center">
                            6
                        </div>

                    </td>

                    <td>
                        <div class="text-center">
                            <button class="btn btn-dark">Delete</button>
                        </div>

                    </td>
                </tr>


                </tbody>
            </table>

        </div>
    </div>
</div>

templates/hoteladmin/CreateBrand.html
{% load crispy_forms_tags %}
<form id="create-brand-form">
{#    <div class="form-row d-flex justify-content-center align-content-center mb-2">#}
{#        <div class="col mx-2 my-sm-1">#}
{#            <input type="text" id="id_brand" name="brand" placeholder="Enter Here..." class="col-sm-8 mx-2">#}
{#            <input type="button" id="create-brand" class="btn-sm btn-dark col-sm-3" value="Create">#}
{#        </div>#}
{#    </div>#}
{#    #}
    {% crispy BrandForm %}
</form>

templates/hoteladmin/CreateSize.html
{% load crispy_forms_tags %}
<form id="create-size-form">
{#    <div class="form-row d-flex justify-content-center align-content-center mb-2">#}
{#        <div class="col mx-2 my-sm-1">#}
{#            <input type="text" id="id_size" name="size" placeholder="Enter Here..." class="col-sm-8 mx-2">#}
{#            <input type="button" id="create-size" class="btn-sm btn-dark col-sm-3" value="Create">#}
{#        </div>#}
{#    </div>#}
    {% crispy SizeForm %}
</form>

templates/hoteladmin/Dashboard.html
{% extends 'hoteladmin/admin.html' %}

{% block Dashboard %}
    <div class="container mt-sm-2">
        <div class="row d-flex justify-content-evenly">

            <div class="col-sm-4 me-2 shadow-lg p-3 bg-body rounded">
                <div class="row">
                    <p><h4>From: {{ fromDate }}</h4></p>
                </div>
                <div class="row">
                    <p><h4>To: {{ toDate }}</h4></p>
                </div>


            </div>
            <div class="col flex-grow-1 shadow-lg p-3 bg-body rounded">

                {% include 'hoteladmin/DashboardDateInput.html' %}

            </div>
        </div>
    </div>


    {% include 'hoteladmin/PieChart_BarDiagram.html' %}


    <div class="container mt-sm-2 ">
        <div class="row d-flex justify-content-center">
            <div class="shadow-lg p-3 bg-body rounded flex-grow-1">

                <div class="text-center">
                    <p>
                    <h4>Sales Report</h4>
                    </p>
                </div>

                <table class="table table-hover">
                    <thead>
                    <th class="col">Bottle</th>
                    <th class="col">Quantity</th>
                    <th class="col">Sold</th>
                    <th class="col">Profit</th>
                    </thead>
                    <tbody>
                    {% for value in table.values %}
                        <tr>
                            {% for info in value %}
                                <td class="col">{{ info }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>
    </div>

    {% include 'water/stockTable.html' %}

    <div class="container mt-sm-2">
        <div class="row d-flex justify-content-between">
            {% include 'hoteladmin/AdminBrandTable.html' %}
            {#        {% include 'AdminBottleTable.html' %}#}
            {% include 'hoteladmin/AdminSizeTable.html' %}
        </div>
    </div>

{% endblock %}

templates/hoteladmin/DashboardDateInput.html
<fieldset class="border p-sm-2 form-group">
    <legend class="w-auto float-none" id="Legend5">
        Date Range
    </legend>
    <form method="POST" action="">
    {% csrf_token %}

        <div class="row">

            <div class="col">
                <div class="form-floating">
                    <input type="date" class="form-control" id="dashboard_from_input"
                           name="dashboard_from"
                           placeholder="From">
                    <label for="dashboard_from_input">From</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating">
                    <input type="date" class="form-control" id="dashboard_from_input"
                           name="dashboard_to"
                           placeholder="To">
                    <label for="dashboard_from_input">From</label>
                </div>
            </div>

        </div>

        <div class="row d-flex justify-content-center">
            <div class="col-3 mt-3 mb-1 ms-5">
                <button type="submit" name="date_submit" class="btn btn-dark">Search</button>
            </div>

        </div>
    </form>

</fieldset>

templates/hoteladmin/PieChart_BarDiagram.html
<div class="container mt-sm-2">
    <div class="row d-flex">
        <div class="col-5 shadow-lg p-3 bg-body rounded">

            {% include "hoteladmin/ProfitPieChart.html" %}

        </div>
        <div class="col flex-grow-1">
            <div class="row d-flex">
                <div class="col shadow-lg p-3 mx-2 mb-2 bg-body rounded" >
                    <div class="row">
                        <p>
                        <h3>Total Sold</h3>
                        </p>
                    </div>
                    <hr>
                    <div class="row d-flex justify-content-end">
                        <div class="col-4">
                            <h4>{{ totalSold }}</h4>
                        </div>

                    </div>
                </div>
                <div class="col shadow-lg p-3 mb-2 bg-body rounded ">
                    <div class="row">
                        <p class="text-start">
                        <h3>Total Profit</h3></p>
                    </div>
                    <hr>
                    <div class="row d-flex justify-content-end">
                        <div class="col-4">
                            <h4>{{ totalProfit }}</h4>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row d-flex">

                <div class="col-sm shadow-lg p-3 ms-2 bg-body rounded">
                    <fieldset class="border p-sm-2 form-group">
                        <legend class="w-auto float-none" id="Legend5">
                            Create Brand
                        </legend>

                        {% include 'hoteladmin/CreateBrand.html' %}

                    </fieldset>

                </div>


            </div>

            <div class="row">

                    <div class="col-sm shadow-lg p-3 mt-2 ms-2 bg-body rounded">
                        <fieldset class="border p-sm-2 form-group">
                            <legend class="w-auto float-none" id="Legend5">
                                Create Size
                            </legend>

                            {% include 'hoteladmin/CreateSize.html' %}

                        </fieldset>

                    </div>
            </div>

        </div>


    </div>
</div>

templates/hoteladmin/ProfitPieChart.html
<canvas id="myChart" width="400" height="400"></canvas>
<script>
    const ctx = document.getElementById('myChart').getContext('2d');
    const myChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: [{% for brand in profitInfo.keys %}
                '{{ brand }}',
            {% endfor %}],
            datasets: [{
                label: '# of Votes',
                data: [ {% for profit in profitInfo.values %} {{ profit }},{% endfor %} ],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>

templates/hoteladmin/admin.html
{% load crispy_forms_tags %}
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.0/dist/chart.min.js"></script>


    <title>Dashboard</title>
</head>
<body style="background-color: rgb(214,214,214)">
<style>
    .asteriskField {
        display: none;
    }
</style>

{% include 'commonHTML/navbar.html' %}


{% block Dashboard %}
{% endblock %}

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{% include 'commonHTML/ajax.html' %}
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->


</body>
</html>